package com.pojo;

// Generated 17 Apr, 2019 1:19:42 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Appo generated by hbm2java
 */
public class Appo implements java.io.Serializable {

	private Integer aid;
	private Doctor doctor;
	private Pregister pregister;
	private String time;
	private Date date;
	private String day;

	public Appo() {
	}

	public Appo(Doctor doctor, Pregister pregister, String time, Date date, String day) {
		this.doctor = doctor;
		this.pregister = pregister;
		this.time = time;
		this.date = date;
		this.day = day;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	public Pregister getPregister() {
		return this.pregister;
	}

	public void setPregister(Pregister pregister) {
		this.pregister = pregister;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

}
