package com.pojo;

// Generated 17 Apr, 2019 1:19:42 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Bill generated by hbm2java
 */
public class Bill implements java.io.Serializable {

	private Integer bid;
	private Pdisease pdisease;
	private Pregister pregister;
	private Integer generalDay;
	private Integer generalTotal;
	private Integer specialDay;
	private Integer specialTotal;
	private String acNonac;
	private Integer icuDay;
	private Integer icuTotal;
	private Integer otherCharges;
	private String reason;
	private Integer operationTheater;
	private Integer labTestCharges;
	private Integer consultingFees;
	private String payment;
	private Integer medicalCharges;
	private Long total;
	private Date date;
	private String status;

	public Bill() {
	}

	public Bill(Pdisease pdisease, Pregister pregister, Integer generalDay, Integer generalTotal, Integer specialDay,
			Integer specialTotal, String acNonac, Integer icuDay, Integer icuTotal, Integer otherCharges,
			String reason, Integer operationTheater, Integer labTestCharges, Integer consultingFees, String payment,
			Integer medicalCharges, Long total, Date date, String status) {
		this.pdisease = pdisease;
		this.pregister = pregister;
		this.generalDay = generalDay;
		this.generalTotal = generalTotal;
		this.specialDay = specialDay;
		this.specialTotal = specialTotal;
		this.acNonac = acNonac;
		this.icuDay = icuDay;
		this.icuTotal = icuTotal;
		this.otherCharges = otherCharges;
		this.reason = reason;
		this.operationTheater = operationTheater;
		this.labTestCharges = labTestCharges;
		this.consultingFees = consultingFees;
		this.payment = payment;
		this.medicalCharges = medicalCharges;
		this.total = total;
		this.date = date;
		this.status = status;
	}

	public Integer getBid() {
		return this.bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

	public Pdisease getPdisease() {
		return this.pdisease;
	}

	public void setPdisease(Pdisease pdisease) {
		this.pdisease = pdisease;
	}

	public Pregister getPregister() {
		return this.pregister;
	}

	public void setPregister(Pregister pregister) {
		this.pregister = pregister;
	}

	public Integer getGeneralDay() {
		return this.generalDay;
	}

	public void setGeneralDay(Integer generalDay) {
		this.generalDay = generalDay;
	}

	public Integer getGeneralTotal() {
		return this.generalTotal;
	}

	public void setGeneralTotal(Integer generalTotal) {
		this.generalTotal = generalTotal;
	}

	public Integer getSpecialDay() {
		return this.specialDay;
	}

	public void setSpecialDay(Integer specialDay) {
		this.specialDay = specialDay;
	}

	public Integer getSpecialTotal() {
		return this.specialTotal;
	}

	public void setSpecialTotal(Integer specialTotal) {
		this.specialTotal = specialTotal;
	}

	public String getAcNonac() {
		return this.acNonac;
	}

	public void setAcNonac(String acNonac) {
		this.acNonac = acNonac;
	}

	public Integer getIcuDay() {
		return this.icuDay;
	}

	public void setIcuDay(Integer icuDay) {
		this.icuDay = icuDay;
	}

	public Integer getIcuTotal() {
		return this.icuTotal;
	}

	public void setIcuTotal(Integer icuTotal) {
		this.icuTotal = icuTotal;
	}

	public Integer getOtherCharges() {
		return this.otherCharges;
	}

	public void setOtherCharges(Integer otherCharges) {
		this.otherCharges = otherCharges;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Integer getOperationTheater() {
		return this.operationTheater;
	}

	public void setOperationTheater(Integer operationTheater) {
		this.operationTheater = operationTheater;
	}

	public Integer getLabTestCharges() {
		return this.labTestCharges;
	}

	public void setLabTestCharges(Integer labTestCharges) {
		this.labTestCharges = labTestCharges;
	}

	public Integer getConsultingFees() {
		return this.consultingFees;
	}

	public void setConsultingFees(Integer consultingFees) {
		this.consultingFees = consultingFees;
	}

	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	public Integer getMedicalCharges() {
		return this.medicalCharges;
	}

	public void setMedicalCharges(Integer medicalCharges) {
		this.medicalCharges = medicalCharges;
	}

	public Long getTotal() {
		return this.total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
