package com.pojo;

// Generated 17 Apr, 2019 1:19:42 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer deptid;
	private String deptname;
	private Set doctors = new HashSet(0);

	public Department() {
	}

	public Department(String deptname, Set doctors) {
		this.deptname = deptname;
		this.doctors = doctors;
	}

	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public Set getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set doctors) {
		this.doctors = doctors;
	}

}
