package com.pojo;

// Generated 17 Apr, 2019 1:19:42 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {

	private Integer hid;
	private Pdisease pdisease;
	private Pregister pregister;
	private Report report;
	private Date time;

	public History() {
	}

	public History(Pdisease pdisease, Pregister pregister, Report report, Date time) {
		this.pdisease = pdisease;
		this.pregister = pregister;
		this.report = report;
		this.time = time;
	}

	public Integer getHid() {
		return this.hid;
	}

	public void setHid(Integer hid) {
		this.hid = hid;
	}

	public Pdisease getPdisease() {
		return this.pdisease;
	}

	public void setPdisease(Pdisease pdisease) {
		this.pdisease = pdisease;
	}

	public Pregister getPregister() {
		return this.pregister;
	}

	public void setPregister(Pregister pregister) {
		this.pregister = pregister;
	}

	public Report getReport() {
		return this.report;
	}

	public void setReport(Report report) {
		this.report = report;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
