package com.pojo;

// Generated 17 Apr, 2019 1:19:42 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pdisease generated by hbm2java
 */
public class Pdisease implements java.io.Serializable {

	private Integer pdid;
	private Doctor doctor;
	private Pregister pregister;
	private String diseaseName;
	private Date admissionDate;
	private String wardno;
	private String bedno;
	private String inchargeName;
	private Set bills = new HashSet(0);
	private Set reports = new HashSet(0);
	private Set histories = new HashSet(0);

	public Pdisease() {
	}

	public Pdisease(Doctor doctor, Pregister pregister, String diseaseName, Date admissionDate, String wardno,
			String bedno, String inchargeName, Set bills, Set reports, Set histories) {
		this.doctor = doctor;
		this.pregister = pregister;
		this.diseaseName = diseaseName;
		this.admissionDate = admissionDate;
		this.wardno = wardno;
		this.bedno = bedno;
		this.inchargeName = inchargeName;
		this.bills = bills;
		this.reports = reports;
		this.histories = histories;
	}

	public Integer getPdid() {
		return this.pdid;
	}

	public void setPdid(Integer pdid) {
		this.pdid = pdid;
	}

	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	public Pregister getPregister() {
		return this.pregister;
	}

	public void setPregister(Pregister pregister) {
		this.pregister = pregister;
	}

	public String getDiseaseName() {
		return this.diseaseName;
	}

	public void setDiseaseName(String diseaseName) {
		this.diseaseName = diseaseName;
	}

	public Date getAdmissionDate() {
		return this.admissionDate;
	}

	public void setAdmissionDate(Date admissionDate) {
		this.admissionDate = admissionDate;
	}

	public String getWardno() {
		return this.wardno;
	}

	public void setWardno(String wardno) {
		this.wardno = wardno;
	}

	public String getBedno() {
		return this.bedno;
	}

	public void setBedno(String bedno) {
		this.bedno = bedno;
	}

	public String getInchargeName() {
		return this.inchargeName;
	}

	public void setInchargeName(String inchargeName) {
		this.inchargeName = inchargeName;
	}

	public Set getBills() {
		return this.bills;
	}

	public void setBills(Set bills) {
		this.bills = bills;
	}

	public Set getReports() {
		return this.reports;
	}

	public void setReports(Set reports) {
		this.reports = reports;
	}

	public Set getHistories() {
		return this.histories;
	}

	public void setHistories(Set histories) {
		this.histories = histories;
	}

}
