package com.pojo;

// Generated 17 Apr, 2019 1:19:42 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregister generated by hbm2java
 */
public class Pregister implements java.io.Serializable {

	private Integer pid;
	private String pname;
	private String pemailid;
	private Long pmobileNumber;
	private String paddress;
	private Date dob;
	private String gender;
	private String password;
	private Integer otp;
	private Set bills = new HashSet(0);
	private Set pdiseases = new HashSet(0);
	private Set histories = new HashSet(0);
	private Set appos = new HashSet(0);

	public Pregister() {
	}

	public Pregister(String pname, String pemailid, Long pmobileNumber, String paddress, Date dob, String gender,
			String password, Integer otp, Set bills, Set pdiseases, Set histories, Set appos) {
		this.pname = pname;
		this.pemailid = pemailid;
		this.pmobileNumber = pmobileNumber;
		this.paddress = paddress;
		this.dob = dob;
		this.gender = gender;
		this.password = password;
		this.otp = otp;
		this.bills = bills;
		this.pdiseases = pdiseases;
		this.histories = histories;
		this.appos = appos;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPemailid() {
		return this.pemailid;
	}

	public void setPemailid(String pemailid) {
		this.pemailid = pemailid;
	}

	public Long getPmobileNumber() {
		return this.pmobileNumber;
	}

	public void setPmobileNumber(Long pmobileNumber) {
		this.pmobileNumber = pmobileNumber;
	}

	public String getPaddress() {
		return this.paddress;
	}

	public void setPaddress(String paddress) {
		this.paddress = paddress;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getOtp() {
		return this.otp;
	}

	public void setOtp(Integer otp) {
		this.otp = otp;
	}

	public Set getBills() {
		return this.bills;
	}

	public void setBills(Set bills) {
		this.bills = bills;
	}

	public Set getPdiseases() {
		return this.pdiseases;
	}

	public void setPdiseases(Set pdiseases) {
		this.pdiseases = pdiseases;
	}

	public Set getHistories() {
		return this.histories;
	}

	public void setHistories(Set histories) {
		this.histories = histories;
	}

	public Set getAppos() {
		return this.appos;
	}

	public void setAppos(Set appos) {
		this.appos = appos;
	}

}
