package com.pojo;

// Generated 17 Apr, 2019 1:19:42 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Report generated by hbm2java
 */
public class Report implements java.io.Serializable {

	private Integer rid;
	private Pdisease pdisease;
	private String rname;
	private byte[] rphoto;
	private Set histories = new HashSet(0);

	public Report() {
	}

	public Report(Pdisease pdisease, String rname, byte[] rphoto, Set histories) {
		this.pdisease = pdisease;
		this.rname = rname;
		this.rphoto = rphoto;
		this.histories = histories;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public Pdisease getPdisease() {
		return this.pdisease;
	}

	public void setPdisease(Pdisease pdisease) {
		this.pdisease = pdisease;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	public byte[] getRphoto() {
		return this.rphoto;
	}

	public void setRphoto(byte[] rphoto) {
		this.rphoto = rphoto;
	}

	public Set getHistories() {
		return this.histories;
	}

	public void setHistories(Set histories) {
		this.histories = histories;
	}

}
